pipeline {
  agent any
  tools {
    gradle '8.2.1'
  }
  stages {
    stage('SCM') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'gradle clean build'
      }
    }
    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('sonarqube') {
          sh 'gradle sonar'
        }
      }
    }
    stage('Generate jar') {
      steps {
        sh 'gradle assemble'
      }
    }
  }
}
