node {
  stage('SCM') {
    checkout scm
  }
  stage('Build') {
    sh "gradle clean install"
  }
  stage('Generate jar') {
    sh "gradle package"
  }
  stage('SonarQube Analysis') {
    withSonarQubeEnv() {
      sh "gradle sonar"
    }
  }
}