pipeline {
  agent any
  tools {
    gradle '8.2.1'
  }
  stages {
    stage('SCM') {
      checkout scm
    }
    stage('Build') {
      sh 'gradle clean install'
    }
    stage('Generate jar') {
      sh 'gradle package'
    }
    stage('SonarQube Analysis') {
      withSonarQubeEnv() {
        sh 'gradle sonar'
      }
    }
  }
}
